"""add interest tags support

Revision ID: 26ef4d388ddb
Revises: feb7a31e9ed1
Create Date: 2025-10-19 13:34:44.693479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '26ef4d388ddb'
down_revision: Union[str, Sequence[str], None] = 'feb7a31e9ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    interest_tag_table = op.create_table('interesttag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interesttag_name'), 'interesttag', ['name'], unique=True)
    op.create_table('userinteresttag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['interesttag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # Seed predefined interest tags
    now = datetime.utcnow()
    predefined_tags = [
        {'name': '文學', 'is_predefined': True, 'created_at': now},
        {'name': '商業', 'is_predefined': True, 'created_at': now},
        {'name': '科技', 'is_predefined': True, 'created_at': now},
        {'name': '藝術', 'is_predefined': True, 'created_at': now},
        {'name': '歷史', 'is_predefined': True, 'created_at': now},
        {'name': '哲學', 'is_predefined': True, 'created_at': now},
        {'name': '心理學', 'is_predefined': True, 'created_at': now},
        {'name': '科幻', 'is_predefined': True, 'created_at': now},
        {'name': '推理', 'is_predefined': True, 'created_at': now},
        {'name': '傳記', 'is_predefined': True, 'created_at': now},
    ]
    op.bulk_insert(interest_tag_table, predefined_tags)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinteresttag')
    op.drop_index(op.f('ix_interesttag_name'), table_name='interesttag')
    op.drop_table('interesttag')
    # ### end Alembic commands ###
