"""Add login protection fields to user

Revision ID: 7c65718e9851
Revises: ee6dbb92555d
Create Date: 2025-10-15 12:55:59.995598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c65718e9851'
down_revision: Union[str, Sequence[str], None] = 'ee6dbb92555d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 新增欄位時使用 server_default 確保現有資料有預設值
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    # ### end Alembic commands ###
