"""add_created_at_to_notification

Revision ID: 7cfe7f4c1453
Revises: b5b7ed9af23c
Create Date: 2025-11-08 09:42:10.768576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cfe7f4c1453'
down_revision: Union[str, Sequence[str], None] = 'b5b7ed9af23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_password_reset_expires'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_password_reset_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_column('discussiontopic', 'created_at')
    
    # Add created_at column as nullable first
    op.add_column('notification', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE notification SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # Make the column NOT NULL
    op.alter_column('notification', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'created_at')
    op.add_column('discussiontopic', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_password_reset_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_password_reset_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_password_reset_expires'), 'password_reset_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
