"""Add comment_count to DiscussionTopic

Revision ID: 931f80d46dc0
Revises: ed5146efcb57
Create Date: 2025-10-31 08:03:05.020787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931f80d46dc0'
down_revision: Union[str, Sequence[str], None] = 'ed5146efcb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussiontopic', sa.Column('comment_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussiontopic', 'comment_count')
    # ### end Alembic commands ###
