"""add_club_tags_and_cover_image

Revision ID: 96905e63a696
Revises: a55b55a8849e
Create Date: 2025-10-24 16:20:35.396186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96905e63a696'
down_revision: Union[str, Sequence[str], None] = 'a55b55a8849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubtag_name'), 'clubtag', ['name'], unique=True)
    op.create_table('bookclubtaglink',
    sa.Column('book_club_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_club_id'], ['bookclub.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['clubtag.id'], ),
    sa.PrimaryKeyConstraint('book_club_id', 'tag_id')
    )
    op.add_column('bookclub', sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('bookclub', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bookclub', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub', 'updated_at')
    op.drop_column('bookclub', 'created_at')
    op.drop_column('bookclub', 'cover_image_url')
    op.drop_table('bookclubtaglink')
    op.drop_index(op.f('ix_clubtag_name'), table_name='clubtag')
    op.drop_table('clubtag')
    # ### end Alembic commands ###
