"""Update member roles

Revision ID: 9e4ac07fa28e
Revises: c50ef87cb809
Create Date: 2025-10-26 06:32:06.461069

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9e4ac07fa28e'
down_revision: Union[str, Sequence[str], None] = 'c50ef87cb809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
