"""Merge heads

Revision ID: a55b55a8849e
Revises: 8dc583baeb87, c0ad6aeb438a
Create Date: 2025-10-23 08:00:00.000000

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a55b55a8849e'
down_revision: Union[str, Sequence[str], None] = ('8dc583baeb87', 'c0ad6aeb438a')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
