"""add_created_at_to_discussiontopic

Revision ID: b5b7ed9af23c
Revises: b2a6d580feb2
Create Date: 2025-11-07 10:33:48.514352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b5b7ed9af23c'
down_revision: Union[str, Sequence[str], None] = 'b2a6d580feb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at column with nullable=True first, then set default and make it NOT NULL
    op.add_column('discussioncomment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE discussioncomment SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('discussioncomment', 'created_at', nullable=False)
    
    op.add_column('discussiontopic', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE discussiontopic SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.alter_column('discussiontopic', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussiontopic', 'created_at')
    op.drop_column('discussioncomment', 'created_at')
    # ### end Alembic commands ###
