"""Add discussion topic and comment models

Revision ID: ed5146efcb57
Revises: d4c044f9fbde
Create Date: 2025-10-29 16:48:20.324802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5146efcb57'
down_revision: Union[str, Sequence[str], None] = 'd4c044f9fbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussionpost')
    op.drop_table('discussionthread')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_column('user', 'oauth_provider')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('oauth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    op.create_table('discussionthread',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('discussionthread_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('book_club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='discussionthread_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_club_id'], ['bookclub.id'], name='discussionthread_book_club_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discussionthread_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('discussionpost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('discussionpost_author_id_fkey')),
    sa.ForeignKeyConstraint(['thread_id'], ['discussionthread.id'], name=op.f('discussionpost_thread_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('discussionpost_pkey'))
    )
    # ### end Alembic commands ###
