"""Add OAuth support to user model

Revision ID: feb7a31e9ed1
Revises: 7c65718e9851
Create Date: 2025-10-15 13:41:21.613122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'feb7a31e9ed1'
down_revision: Union[str, Sequence[str], None] = '7c65718e9851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'oauth_provider')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
